[package]
edition = "2021"
name = "aruna_server"
version = "1.0.0"
description = "Server application for AOS (Aruna Object Storage)"
repository = "https://github.com/ArunaStorage/ArunaServer"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
aruna-rust-api = "1.1.0-rc.5"
bigdecimal = "0.3.0"
chrono = "0.4.24"
diesel = {version = "2.1.0", features = ["postgres", "uuid", "r2d2", "chrono", "numeric", "serde_json"]}
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
dotenv = "0.15.0"
http = "0.2.9"
itertools = "0.10.5"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
log = "0.4.17"
openssl = "0.10.50"
prost = "0.11.8"
prost-types = "0.11.8"
r2d2 = { version = ">= 0.8.10, < 0.9.0"}
rand = "0.8.5"
rand_core = "0.6.4"
regex = "1.7.3"
reqsign = { version = "0.9.4", features = ["reqwest_request"]}
reqwest = {version = "0.11.16", features = ["json"] }
serde = {version = "1.0.159", features = ["derive"]}
serde_json = "1.0.95"
simple_logger = "4.1.0"
time = "0.3.20"
tokio = {version = "1.27.0", features = ["full"]}
tokio-stream = { version = "0.1.12", features = ["net"] }
toml = "0.7.3"
tonic = "0.9.1"
url = "2.3.1"
uuid = {version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
lettre = "0.10"
diesel-ulid = "=0.1.3-alpha.2"
rusty_ulid = "2.0.0"
kube = {version= "0.82.2", features = ["runtime", "client", "derive"]}
k8s-openapi = { version = "0.18.0", features = ["v1_24"] }
schemars = { version = "0.8.11", features = ["chrono"] }

[dev-dependencies]
serial_test = "2.0.0"
