[package]
edition = "2021"
name = "aruna_server"
version = "1.0.0"
description = "Server application for AOS (Aruna Object Storage)"
repository = "https://github.com/ArunaStorage/ArunaServer"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
aruna-rust-api = "1.1.0-rc.5"
bigdecimal = "0.3.1"
chrono = "0.4.26"
diesel = {version = "2.1.0", features = ["postgres", "uuid", "r2d2", "chrono", "numeric", "serde_json"]}
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
dotenv = "0.15.0"
http = "0.2.9"
itertools = "0.10.5"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
log = "0.4.19"
openssl = "0.10.55"
prost = "0.11.9"
prost-types = "0.11.9"
r2d2 = { version = ">= 0.8.10, < 0.9.0"}
rand = "0.8.5"
rand_core = "0.6.4"
regex = "1.8.4"
reqsign = { version = "0.9.5", features = ["reqwest_request"]}
reqwest = {version = "0.11.18", features = ["json"] }
serde = {version = "1.0.164", features = ["derive"]}
serde_json = "1.0.97"
simple_logger = "4.2.0"
time = "0.3.22"
tokio = {version = "1.28.2", features = ["full"]}
tokio-stream = { version = "0.1.14", features = ["net"] }
toml = "0.7.4"
tonic = "0.9.2"
url = "2.4.0"
uuid = {version = "1.3.4", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
lettre = "0.10"
diesel-ulid = "=0.1.3-alpha.2"
rusty_ulid = "2.0.0"
kube = {version= "0.82.2", features = ["runtime", "client", "derive"]}
k8s-openapi = { version = "0.18.0", features = ["v1_24"] }
schemars = { version = "0.8.12", features = ["chrono"] }

[dev-dependencies]
serial_test = "2.0.0"
