[package]
edition = "2021"
name = "aruna_server"
version = "1.0.0"
description = "Server application for AOS (Aruna Object Storage)"
repository = "https://github.com/ArunaStorage/ArunaServer"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
aruna-rust-api = "2.0.0-alpha.5"
bigdecimal = "0.3.1"
chrono = "0.4.26"
dotenv = "0.15.0"
http = "0.2.9"
itertools = "0.11.0"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
log = "0.4.19"
openssl = "0.10.55"
prost = "0.11.9"
prost-types = "0.11.9"
r2d2 = { version = ">= 0.8.10, < 0.9.0"}
rand = "0.8.5"
rand_core = "0.6.4"
regex = "1.8.4"
reqsign = { version = "0.13.0", features = ["reqwest_request"]}
reqwest = {version = "0.11.18", features = ["json"] }
serde = {version = "1.0.164", features = ["derive"]}
serde_json = {version = "1.0.99", features = ["raw_value"]}
simple_logger = "4.2.0"
time = "0.3.22"
tokio = {version = "1.29.1", features = ["full"]}
tokio-stream = { version = "0.1.14", features = ["net"] }
toml = "0.7.5"
tonic = "0.9.2"
url = "2.4.0"
uuid = {version = "1.4.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
lettre = "0.10"
diesel-ulid = "0.2.0"
rusty_ulid = "2.0.0"
kube = {version= "0.83.0", features = ["runtime", "client", "derive"]}
k8s-openapi = { version = "0.18.0", features = ["v1_24"] }
schemars = { version = "0.8.12", features = ["chrono"] }
sha2 = "0.10.7"
hmac = "0.12.1"
hex = "0.4.3"
base64 = "0.21.2"
tower = "0.4.13"
async-trait = "0.1.71"

# Postgres interaction
tokio-postgres = { version = "0.7.8", features = ["with-uuid-1", "with-serde_json-1", "with-chrono-0_4"] }
postgres-types = { version = "0.2.5", features = ["derive"] }
deadpool-postgres = "0.10.5"
futures = "0.3.28"
postgres-from-row = "=0.5.2"

