[package]
edition = "2021"
name = "aruna_server"
version = "1.1.0-rc.1"
description = "Server application for AOS (Aruna Object Storage)"
repository = "https://github.com/ArunaStorage/ArunaServer"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
diesel = {version = "2.0.3", features = ["postgres", "uuid", "r2d2", "chrono", "numeric"]}
diesel-derive-enum = { version = "2.0.1", features = ["postgres"] }
dotenv = "0.15.0"
http = "0.2.9"
itertools = "0.10.5"
log = "0.4.17"
simple_logger = "4.0.0"
prost = "0.11.7"
prost-types = "0.11.7"
tokio = {version = "1.25.0", features = ["full"]}
tokio-stream = { version = "0.1.12", features = ["net"] }
tonic = "0.8.3"
uuid = {version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
r2d2 = { version = ">= 0.8.10, < 0.9.0"}
rand = "0.8.5"
rand_core = "0.6.4"
jsonwebtoken = "8.2.0"
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
reqwest = {version = "0.11.14", features = ["json"] }
openssl = "0.10.45"
toml = "0.7.2"
aruna-rust-api = "1.0.0-rc.11"
bigdecimal = "0.3.0"
regex = "1.7.1"
lazy_static = "1.4.0"

[dev-dependencies]
serial_test = "1.0.0"
url = "2.3.1"