[package]
edition = "2021"
name = "aruna_server"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
diesel = {version = "2.0.0-rc.0", features = ["postgres", "uuid", "r2d2", "chrono"]}
diesel-derive-enum = { version = "2.0.0-rc.0", features = ["postgres"] }
dotenv = "0.15.0"
http = "0.2.8"
prost = "0.11.0"
prost-types = "0.11.0"
tokio = {version = "1.20.1", features = ["full"]}
tonic = "0.8.0"
uuid = {version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
r2d2 = { version = ">= 0.8.2, < 0.9.0"}
rand = "0.7"
rand_core = "0.5"
jsonwebtoken = "8.1.1"
serde = {version = "1.0", features = ["derive"]}

[build-dependencies]
tonic-build = "0.8.0"

[dev-dependencies]
serial_test = "0.9.0"
