[package]
edition = "2021"
name = "aruna_server"
version = "2.0.0-rc.1"
description = "Server application for AOS (Aruna Object Storage)"
repository = "https://github.com/ArunaStorage/ArunaServer"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-s3 = "1.17.0"
aws-config = "1.0.0"
aws-types = "1.0.0"
anyhow = "1.0.75"
aruna-rust-api = { git = "https://github.com/ArunaStorage/rust-api.git", branch = "pre/beta12" }
async-nats = "0.33.0"
async-channel = "2.0.0"
bincode = "1.3.3"
chrono = "0.4.31"
dotenvy = "0.15.7"
evmap = "10.0.2"
evmap-derive = "0.2.0"
itertools = "0.12.0"
jsonwebtoken = {version = "9.1.0", features = ["use_pem"]}
log = "0.4.20"
meilisearch-sdk = "0.24.2"
prost = "0.12.3"
prost-wkt-types = "0.5.0"
rand = "0.8.5"
rand_core = "0.6.4"
regex = "1.10.2"
reqsign = { version = "0.14.3", features = ["reqwest_request"]}
reqwest = {version = "0.11.22", features = ["json"] }
serde = {version = "1.0.190", features = ["derive"]}
serde_json = {version = "1.0.108", features = ["raw_value"]}
simple_logger = "4.2.0"
time = "0.3.30"
tokio = {version = "1.33.0", features = ["full"]}
tokio-stream = { version = "0.1.14", features = ["net"] }
tonic = {version = "0.11.0", features =["tls", "tls-roots"] }
url = "2.4.1"
uuid = {version = "1.5.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
lettre = "0.11"
diesel-ulid = "0.3.1"
rusty_ulid = "2.0.0"
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
base64 = "0.21.5"
tower = "0.4.13"
async-trait = "0.1.74"
dashmap = {version = "5.5.3", features = ["serde"]}
ahash = "0.8.6"
xxhash-rust = {version="0.8.7", features=["xxh3"]}
lazy_static = "1.4.0"

# Postgres interaction
tokio-postgres = { version = "0.7.10", features = ["with-uuid-1", "with-serde_json-1", "with-chrono-0_4"] }
postgres-types = { version = "0.2.6", features = ["derive"] }
deadpool-postgres = "0.12.1"
futures = "0.3.29"
postgres-from-row = "=0.5.2"

# Policies
cel-parser = "0.6.0"
cel-interpreter = "0.6.0"
