[package]
edition = "2021"
name = "aruna_server"
version = "0.5.0-beta.7"
description = "Server application for AOS (Aruna Object Storage)"
repository = "https://github.com/ArunaStorage/ArunaServer"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
diesel = {version = "2.0.0-rc.1", features = ["postgres", "uuid", "r2d2", "chrono"]}
diesel-derive-enum = { version = "2.0.0-rc.0", features = ["postgres"] }
dotenv = "0.15.0"
http = "0.2.8"
itertools = "0.10.3"
log = "0.4.17"
simple_logger = "4.0.0"
prost = "0.11.0"
prost-types = "0.11.0"
tokio = {version = "1.20.1", features = ["full"]}
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.8.1"
uuid = {version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
r2d2 = { version = ">= 0.8.2, < 0.9.0"}
rand = "0.8.5"
rand_core = "0.6.4"
jsonwebtoken = "8.1.1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
reqwest = {version = "0.11.11", features = ["json"] }
openssl = "0.10.41"
toml = "0.5.9"
aruna-rust-api = "0.5.0-beta.7"

[dev-dependencies]
serial_test = "0.9.0"
lazy_static = "1.4.0"