database_url    = 'host=localhost user=root password=test123 port=26257 dbname=test'
oauth_realminfo = 'http://localhost:8999/aruna.json'

[default_endpoint]
ep_type         = 'S3'
endpoint_name   = 'Default Data Proxy'
endpoint_proxy  = 'http://localhost:8081'
endpoint_host   = 'http://localhost:8081'
endpoint_public = true

[loc_version]
location        = 'FOO'
components = [
  { component_name = 'Bar', semver = {major = 0, minor = 1, patch = 0, labels = ''} }
]
