database_url    = 'host=localhost user=root password=test123 port=26257 dbname=test'
oauth_realminfo = 'http://localhost:8999/aruna.json'

[default_endpoint]
ep_type               = 'S3'
endpoint_name         = 'Default Data Proxy'
endpoint_bundler      = true
endpoint_public       = true
endpoint_serial       = 123456
endpoint_pubkey = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAQRcVuLEdJcrsduL4hU0PtpNPubYVIgx8kZVV/Elv9dI=
-----END PUBLIC KEY-----
"""

[[default_endpoint.endpoint_host_config]]
url = "localhost:1337"
is_primary = true
ssl = false
public = true
feature = "PROXY"

[[default_endpoint.endpoint_host_config]]
url = "localhost:8081"
is_primary = true
ssl = false
public = true
feature = "INTERNAL"

[event_notifications]
emitter_host = 'http://localhost:50053'
emitter_token = 'ThisIsASecretToken'

[loc_version]
location        = 'FOO'
components = [
  { component_name = 'Bar', semver = {major = 0, minor = 1, patch = 0, labels = ''} }
]
