on:
  push:
    branches: [main, dev]
  pull_request:
name: lint
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: cargo doc
        uses: actions-rs/cargo@v1
        if: always()
        with:
          command: doc
          args: --no-deps --all-features
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
