on:
  - push
  - pull_request
name: test
jobs:
  test:
    runs-on: self-hosted
    name: test
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: arduino/setup-protoc@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        run: docker compose -f compose.yaml up -d
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features -- --include-ignored
      - name: Remove docker compose cluster
        run: docker compose rm --force --stop --volumes
        shell: bash
        if: ${{ always() }} # To ensure this step runs even when earlier steps fail
      - name: Clean folder
        uses: colpal/actions-clean@v1
        if: ${{ always() }} # To ensure this step runs even when earlier steps fail
